#端口 8888
server:
  port: 8888
# 应用名
spring:
  application:
    name: mszlu_blog
#数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://8.134.54.237:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: blog
    password: 123456
  redis:
    host: 8.134.54.237
    port: 6379
    password: 123456
  servlet:
    multipart:
      max-request-size: 20MB # 最大上传文件最大值
      max-file-size: 2MB # 单个文件的最大值

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_

qiniu:
  accessKey: UYZYnpboaZLrnF6bwuHYAk9O0ADMBPslKg-gnQ7g
  accessSecretKey: g8qJMcns_HBu-v_phivEpJwi6NV8p9ozhRQpiQXB

